#!/usr/bin/env python3
"""Build the pinned package and audit every public declaration. No third-party Python deps."""
from pathlib import Path
import hashlib
import json
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
RECEIPTS = ROOT / "receipts"
ALLOWED_AXIOMS = {"propext", "Classical.choice", "Quot.sound"}


def run(args: list[str], logfile: str) -> str:
    result = subprocess.run(args, cwd=ROOT, text=True, stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT, check=False)
    (RECEIPTS / logfile).write_text(result.stdout)
    if result.returncode:
        print(result.stdout, file=sys.stderr)
        raise SystemExit(f"Command failed ({result.returncode}): {args}")
    if "warning:" in result.stdout:
        raise SystemExit(f"Warnings require inspection: receipts/{logfile}")
    return result.stdout


def main() -> None:
    RECEIPTS.mkdir(parents=True, exist_ok=True)
    declarations = []
    for source in sorted((ROOT / "Normalizer").glob("*.lean")):
        contents = source.read_text()
        if re.search(r"\b(sorry|admit|axiom|unsafe)\b", contents):
            raise SystemExit(f"Forbidden proof escape in {source}")
        for line_number, line in enumerate(contents.splitlines(), 1):
            match = re.match(r"^(?:noncomputable )?(theorem|def|abbrev) (\w+)", line)
            if match:
                declarations.append({"name": "Normalizer." + match[2], "kind": match[1],
                                     "file": str(source.relative_to(ROOT)), "line": line_number})
    names = [decl["name"] for decl in declarations]
    if len(names) != len(set(names)):
        raise SystemExit("Duplicate exported names require explicit reconciliation")
    audit = "import Normalizer\n\n/-! Complete public declaration audit, generated by scripts/verify.py. -/\n"
    audit += "".join(f"#print axioms {decl['name']}\n" for decl in declarations)
    (ROOT / "AxiomAudit.lean").write_text(audit)
    (RECEIPTS / "declarations.json").write_text(json.dumps(declarations, indent=2) + "\n")
    run(["lake", "build"], "build.log")
    output = run(["lake", "env", "lean", "-DwarningAsError=true", "AxiomAudit.lean"], "axioms.log")
    audited = {}
    for name, axiom_text in re.findall(r"'([^']+)' depends on axioms: \[([^]]*)\]", output):
        audited[name] = set(filter(None, re.split(r",\s*|\s+", axiom_text.strip())))
    for name in re.findall(r"'([^']+)' does not depend on any axioms", output):
        audited[name] = set()
    expected = {decl["name"] for decl in declarations}
    if set(audited) != expected:
        raise SystemExit(f"Audit coverage mismatch: {set(audited) ^ expected}")
    for name, axioms in audited.items():
        if not axioms <= ALLOWED_AXIOMS:
            raise SystemExit(f"Unexpected axioms in {name}: {axioms - ALLOWED_AXIOMS}")
    sources = [ROOT / "Normalizer.lean", ROOT / "AxiomAudit.lean", ROOT / "lean-toolchain",
               ROOT / "lakefile.toml", ROOT / "lake-manifest.json", Path(__file__).resolve()]
    sources += sorted((ROOT / "Normalizer").glob("*.lean"))
    summary = {
        "result": "PASS",
        "public_declarations": len(declarations),
        "public_theorems": sum(decl["kind"] == "theorem" for decl in declarations),
        "examples": (ROOT / "Normalizer/Examples.lean").read_text().count("\nexample "),
        "axioms_used": sorted(set().union(*audited.values())),
        "lean_version": subprocess.check_output(["lake", "env", "lean", "--version"], cwd=ROOT, text=True).strip(),
        "mathlib_commit": subprocess.check_output(["git", "-C", str(ROOT / ".lake/packages/mathlib"),
                                                   "rev-parse", "HEAD"], text=True).strip(),
        "sha256": {str(p.relative_to(ROOT)): hashlib.sha256(p.read_bytes()).hexdigest() for p in sources},
    }
    (RECEIPTS / "verification.json").write_text(json.dumps(summary, indent=2) + "\n")
    print(f"PASS: full build; {summary['public_theorems']} theorems; "
          f"{len(declarations)} declarations audited; {summary['examples']} examples.")
    print("Axioms: " + ", ".join(summary["axioms_used"]))


if __name__ == "__main__":
    main()
