import Mathlib.Algebra.Module.PID
import Mathlib.Algebra.Polynomial.Module.AEval
import Mathlib.LinearAlgebra.AnnihilatingPolynomial
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.RingTheory.Adjoin.Polynomial.Basic
import Mathlib.RingTheory.PowerBasis

/-!
# Cyclic vectors and centralizers

The PID structure theorem supplies a vector whose polynomial annihilator equals
the annihilator of the entire endomorphism.  When the minimal polynomial has
full degree, this gives a cyclic vector and bounds the dimension of the
centralizer.  These facts need no algebraic-closedness or characteristic-zero
assumption.
-/

namespace Normalizer

open Module Polynomial

variable {F V : Type*} [Field F] [AddCommGroup V] [Module F V]

/-- One vector detects every polynomial relation on a finite-dimensional
endomorphism. -/
theorem exists_polynomial_separating_vector [FiniteDimensional F V] (f : Module.End F V) :
    ∃ v : V, ∀ p : F[X], (aeval f p) v = 0 ↔ aeval f p = 0 := by
  obtain ⟨v, hv⟩ :=
    Module.exists_ker_toSpanSingleton_eq_annihilator F[X] (Module.AEval' f)
  refine ⟨(Module.AEval'.of f).symm v, fun p => ?_⟩
  have hmem :
      p ∈ LinearMap.ker (LinearMap.toSpanSingleton F[X] (Module.AEval' f) v) ↔
        p ∈ Module.annihilator F[X] (Module.AEval' f) := by rw [hv]
  rw [LinearMap.mem_ker, LinearMap.toSpanSingleton_apply,
    Module.AEval.annihilator_eq_ker_aeval, RingHom.mem_ker] at hmem
  exact hmem

/-- Evaluation at a separating vector is injective on the polynomial algebra
generated by the endomorphism. -/
theorem polynomial_evaluation_injective (f : Module.End F V) (v : V)
    (hv : ∀ p : F[X], (aeval f p) v = 0 ↔ aeval f p = 0) :
    Function.Injective (fun x : Algebra.adjoin F {f} => (x : Module.End F V) v) := by
  intro x y hxy
  obtain ⟨p, hp⟩ := Algebra.adjoin_eq_exists_aeval F f (x - y)
  have hpv : (aeval f p) v = 0 := by
    rw [hp]
    change (x : Module.End F V) v - (y : Module.End F V) v = 0
    exact sub_eq_zero.mpr hxy
  have hp0 := (hv p).mp hpv
  apply sub_eq_zero.mp
  apply Subtype.ext
  exact hp.symm.trans hp0

/-- A separating vector has independent iterates up to the degree of the
minimal polynomial. -/
theorem separating_vector_linearIndependent_powers (f : Module.End F V) (v : V)
    (hv : ∀ p : F[X], (aeval f p) v = 0 ↔ aeval f p = 0) :
    LinearIndependent F (fun i : Fin (minpoly F f).natDegree => (f ^ (i : ℕ)) v) := by
  let ev : Module.End F V →ₗ[F] V := LinearMap.applyₗ v
  have hspan : Submodule.span F (Set.range (fun i : Fin (minpoly F f).natDegree =>
      f ^ (i : ℕ))) ≤ (Algebra.adjoin F {f}).toSubmodule := by
    apply Submodule.span_le.mpr
    rintro _ ⟨i, rfl⟩
    exact (Algebra.adjoin F {f}).pow_mem (Algebra.self_mem_adjoin_singleton F f) _
  have hev : Set.InjOn ev (Submodule.span F (Set.range
      (fun i : Fin (minpoly F f).natDegree => f ^ (i : ℕ)))) := by
    intro x hx y hy hxy
    have he : (⟨x, hspan hx⟩ : Algebra.adjoin F {f}) = ⟨y, hspan hy⟩ :=
      polynomial_evaluation_injective f v hv hxy
    exact congrArg Subtype.val he
  exact (linearIndependent_pow f).map_injOn ev hev

/-- Full minimal-polynomial degree gives a vector generating the entire space
under polynomial evaluation. -/
theorem exists_polynomial_cyclic_vector [FiniteDimensional F V] (f : Module.End F V)
    (hd : (minpoly F f).natDegree = Module.finrank F V) :
    ∃ v : V, ∀ w : V, ∃ p : F[X], (aeval f p) v = w := by
  obtain ⟨v, hv⟩ := exists_polynomial_separating_vector f
  have htop := (separating_vector_linearIndependent_powers f v hv).span_eq_top_of_card_eq_finrank'
    (by simpa using hd)
  refine ⟨v, fun w => ?_⟩
  have hw : w ∈ Submodule.span F (Set.range
      (fun i : Fin (minpoly F f).natDegree => (f ^ (i : ℕ)) v)) := by
    rw [htop]
    trivial
  induction hw using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨i, rfl⟩ := hx
    exact ⟨X ^ (i : ℕ), by simp⟩
  | zero => exact ⟨0, by simp⟩
  | add x y hx hy ihx ihy =>
    obtain ⟨p, hp⟩ := ihx
    obtain ⟨q, hq⟩ := ihy
    exact ⟨p + q, by simp [hp, hq]⟩
  | smul c x hx ih =>
    obtain ⟨p, hp⟩ := ih
    exact ⟨c • p, by simp [hp]⟩

/-- Evaluate an element of the centralizer at a vector. -/
def centralizerEvaluation (f : Module.End F V) (v : V) :
    Subalgebra.centralizer F {f} →ₗ[F] V where
  toFun x := (x : Module.End F V) v
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- An endomorphism commuting with a cyclic operator is determined by its
value at a cyclic vector. -/
theorem centralizerEvaluation_injective (f : Module.End F V) (v : V)
    (hv : ∀ w : V, ∃ p : F[X], (aeval f p) v = w) :
    Function.Injective (centralizerEvaluation f v) := by
  intro x y hxy
  apply Subtype.ext
  ext w
  obtain ⟨p, rfl⟩ := hv w
  have hxf : Commute (x : Module.End F V) f :=
    (((Subalgebra.mem_centralizer_iff F).mp x.property) f (Set.mem_singleton f)).symm
  have hyf : Commute (y : Module.End F V) f :=
    (((Subalgebra.mem_centralizer_iff F).mp y.property) f (Set.mem_singleton f)).symm
  have hxp := Algebra.commute_of_mem_adjoin_singleton_of_commute
    (Polynomial.aeval_mem_adjoin_singleton F f (p := p)) hxf
  have hyp := Algebra.commute_of_mem_adjoin_singleton_of_commute
    (Polynomial.aeval_mem_adjoin_singleton F f (p := p)) hyf
  calc
    (x : Module.End F V) ((aeval f p) v) =
        (aeval f p) ((x : Module.End F V) v) := LinearMap.congr_fun hxp.eq v
    _ = (aeval f p) ((y : Module.End F V) v) := congrArg (aeval f p) hxy
    _ = (y : Module.End F V) ((aeval f p) v) := (LinearMap.congr_fun hyp.eq v).symm

/-- The centralizer of an operator with full minimal-polynomial degree has
dimension at most the dimension of its representation space. -/
theorem centralizer_finrank_le_of_natDegree_eq_finrank [FiniteDimensional F V] (f : Module.End F V)
    (hd : (minpoly F f).natDegree = Module.finrank F V) :
    Module.finrank F (Subalgebra.centralizer F {f}) ≤ Module.finrank F V := by
  obtain ⟨v, hv⟩ := exists_polynomial_cyclic_vector f hd
  exact LinearMap.finrank_le_finrank_of_injective (centralizerEvaluation_injective f v hv)

/-- Vanishing at a cyclic vector detects a commuting endomorphism. -/
theorem commuting_eq_zero_of_cyclic_vector (f g : Module.End F V) (v : V)
    (hv : ∀ w : V, ∃ p : F[X], (aeval f p) v = w)
    (hgf : Commute g f) (hgv : g v = 0) : g = 0 := by
  have hg : g ∈ Subalgebra.centralizer F {f} := by
    rw [Subalgebra.mem_centralizer_iff F]
    simpa using hgf.symm.eq
  have he : (⟨g, hg⟩ : Subalgebra.centralizer F {f}) = 0 :=
    centralizerEvaluation_injective f v hv hgv
  exact congrArg Subtype.val he

/-- Independent line-normalizer lifts for a cyclic operator occupy at most
`dim V - 1` dimensions.  The functional `τ` is instantiated by trace.  The
boundary-bracket identity is unnecessary in this full-degree branch. -/
theorem cyclic_normalizer_lift_finrank [FiniteDimensional F V]
    {W : Type*} [AddCommGroup W] [Module F W] [FiniteDimensional F W]
    (f : Module.End F V) (hf : f ≠ 0)
    (hd : (minpoly F f).natDegree = Module.finrank F V)
    (τ : Module.End F V →ₗ[F] F) (hτ1 : τ 1 ≠ 0) (hτf : τ f = 0)
    (J : W →ₗ[F] Module.End F V) (χ : W →ₗ[F] F)
    (hτJ : ∀ x, τ (J x) = 0)
    (hact : ∀ x, J x * f - f * J x = χ x • f)
    (hinj : ∀ x, (∃ z : F, J x = z • f) → x = 0) :
    Module.finrank F W + 1 ≤ Module.finrank F V := by
  obtain ⟨v, hv⟩ := exists_polynomial_cyclic_vector f hd
  let Φ : (F × F × W) →ₗ[F] (V × F) :=
    { toFun := fun a => ((a.1 • (1 : Module.End F V) + a.2.1 • f + J a.2.2) v, χ a.2.2)
      map_add' := by
        intro a b
        apply Prod.ext <;> simp [add_smul, add_assoc, add_left_comm, add_comm]
      map_smul' := by
        intro c a
        apply Prod.ext <;> simp [smul_add, smul_smul] }
  have hΦ : Function.Injective Φ := by
    apply LinearMap.ker_eq_bot.mp
    apply LinearMap.ker_eq_bot'.mpr
    rintro ⟨a, b, x⟩ hx
    have hχ : χ x = 0 := congrArg Prod.snd hx
    let g : Module.End F V := a • 1 + b • f + J x
    have hgv : g v = 0 := congrArg Prod.fst hx
    have hJf : Commute (J x) f := by
      exact sub_eq_zero.mp (by simpa [hχ] using hact x)
    have hgf : Commute g f :=
      (((Commute.one_left f).smul_left a).add_left ((Commute.refl f).smul_left b)).add_left hJf
    have hg0 : g = 0 := commuting_eq_zero_of_cyclic_vector f g v hv hgf hgv
    have ha : a = 0 := by
      have ht := congrArg τ hg0
      have hamul : a * τ 1 = 0 := by simpa [g, hτf, hτJ x] using ht
      exact (mul_eq_zero.mp hamul).resolve_right hτ1
    have hJx : J x = -b • f := by
      have hsum : b • f + J x = 0 := by simpa [g, ha] using hg0
      exact (eq_neg_of_add_eq_zero_right hsum).trans (neg_smul b f).symm
    have hxx : x = 0 := hinj x ⟨-b, hJx⟩
    have hb : b = 0 := by
      have hbsmul : b • f = 0 := by simpa [g, ha, hxx] using hg0
      exact (smul_eq_zero.mp hbsmul).resolve_right hf
    simp [ha, hb, hxx]
  have hdim := LinearMap.finrank_le_finrank_of_injective hΦ
  simp only [Module.finrank_prod, Module.finrank_self] at hdim
  omega

end Normalizer
