import Mathlib.Algebra.Polynomial.Laurent
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.Data.Int.Interval

/-! Finite generation of a two-chart Laurent quotient. The chart subspaces
are generated by nonnegative and nonpositive powers; their quotient is
proved finite over the coefficient ring by constructing a bounded window. -/
noncomputable section
namespace Normalizer
open LaurentPolynomial
open scoped LaurentPolynomial
universe u v w
variable (k : Type u) [CommRing k] {M : Type v} [AddCommGroup M]
  [Module k M] [Module k[T;T⁻¹] M]
  {ι : Type w}

/-- The coefficient-ring span of the indicated Laurent powers of a family. -/
def laurentSpan (v : ι → M) (s : Set ℤ) : Submodule k M :=
  Submodule.span k {x | ∃ i n, n ∈ s ∧ x = (T n : k[T;T⁻¹]) • v i}

/-- Every indicated translate belongs to its actual coefficient-ring span. -/
theorem laurentSpan_generator (v : ι → M) (s : Set ℤ) (i : ι) (n : ℤ) (hn : n ∈ s) :
    (T n : k[T;T⁻¹]) • v i ∈ laurentSpan k v s :=
  Submodule.subset_span ⟨i, n, hn, rfl⟩

variable [IsScalarTower k k[T;T⁻¹] M]

private theorem laurent_shift_monomial (n m : ℤ) (a : k) (x : M) :
    (T n : k[T;T⁻¹]) • ((C a * T m) • x) = a • ((T (n + m) : k[T;T⁻¹]) • x) := by
  rw [mul_smul, C_eq_algebraMap, algebraMap_smul, smul_comm,
    ← mul_smul, ← T_add]

/-- Restricting a Laurent span to the coefficient ring gives precisely the
span of all integer translates of the original family. -/
theorem laurentSpan_univ (v : ι → M) :
    laurentSpan k v Set.univ =
      (Submodule.span k[T;T⁻¹] (Set.range v)).restrictScalars k := by
  apply le_antisymm
  · apply Submodule.span_le.mpr
    rintro x ⟨i, n, _, rfl⟩
    exact (Submodule.span k[T;T⁻¹] (Set.range v)).smul_mem _
      (Submodule.subset_span (Set.mem_range_self i))
  · intro x hx
    have h : ∀ n : ℤ, (T n : k[T;T⁻¹]) • x ∈ laurentSpan k v Set.univ := by
      induction hx using Submodule.span_induction with
      | mem y hy =>
        obtain ⟨i, rfl⟩ := hy
        exact fun n => laurentSpan_generator k v Set.univ i n (Set.mem_univ n)
      | zero => intro n; simp
      | add x y hx hy ihx ihy =>
        intro n
        rw [smul_add]
        exact Submodule.add_mem _ (ihx n) (ihy n)
      | smul r x hx ih =>
        induction r using LaurentPolynomial.induction_on' with
        | add a b ha hb =>
          intro n
          rw [add_smul, smul_add]
          exact Submodule.add_mem _ (ha n) (hb n)
        | C_mul_T m a =>
          intro n
          rw [laurent_shift_monomial]
          exact Submodule.smul_mem _ a (ih (n + m))
    simpa using h 0

/-- Any element generated over the Laurent ring by a family has all
sufficiently negative translates in its nonpositive-power span. -/
theorem laurent_span_eventually_nonpositive (v : ι → M) {x : M}
    (hx : x ∈ Submodule.span k[T;T⁻¹] (Set.range v)) :
    ∃ b : ℤ, ∀ n ≤ b, (T n : k[T;T⁻¹]) • x ∈ laurentSpan k v (Set.Iic 0) := by
  let P (x : M) := ∃ b : ℤ, ∀ n ≤ b,
    (T n : k[T;T⁻¹]) • x ∈ laurentSpan k v (Set.Iic 0)
  have hAdd {x y : M} (hx : P x) (hy : P y) : P (x + y) := by
    obtain ⟨a, ha⟩ := hx
    obtain ⟨b, hb⟩ := hy
    refine ⟨min a b, fun n hn => ?_⟩
    rw [smul_add]
    exact Submodule.add_mem _ (ha n (hn.trans (min_le_left _ _)))
      (hb n (hn.trans (min_le_right _ _)))
  change P x
  induction hx using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨i, rfl⟩ := hy
    exact ⟨0, fun n hn => laurentSpan_generator k v (Set.Iic 0) i n hn⟩
  | zero => exact ⟨0, fun n _ => by simp⟩
  | add x y hx hy ihx ihy => exact hAdd ihx ihy
  | smul r x hx ih =>
    induction r using LaurentPolynomial.induction_on' with
    | add a b ha hb => simpa only [add_smul] using hAdd ha hb
    | C_mul_T m a =>
      obtain ⟨b, hb⟩ := ih
      refine ⟨b - m, fun n hn => ?_⟩
      rw [laurent_shift_monomial]
      exact Submodule.smul_mem _ a (hb (n + m) (by omega))

/-- Finite Laurent generators and negative-tail bounds construct an explicit
finite window spanning the quotient by the two given chart subspaces. -/
theorem laurent_twoChart_window [Finite ι] (v : ι → M)
    (hv : Submodule.span k[T;T⁻¹] (Set.range v) = ⊤)
    (N : Submodule k M) (hpos : laurentSpan k v (Set.Ici 0) ≤ N)
    (b : ℤ) (hneg : ∀ i n, n ≤ b → (T n : k[T;T⁻¹]) • v i ∈ N) :
    Submodule.span k (Set.range (fun p : ι × ↥(Finset.Icc b 0) =>
      N.mkQ ((T (p.2 : ℤ) : k[T;T⁻¹]) • v p.1))) = ⊤ := by
  let W := Submodule.span k (Set.range (fun p : ι × ↥(Finset.Icc b 0) =>
    N.mkQ ((T (p.2 : ℤ) : k[T;T⁻¹]) • v p.1)))
  have hgen (i : ι) (n : ℤ) : N.mkQ ((T n : k[T;T⁻¹]) • v i) ∈ W := by
    by_cases hn : 0 ≤ n
    · have hz : N.mkQ ((T n : k[T;T⁻¹]) • v i) = 0 :=
        (Submodule.Quotient.mk_eq_zero N).mpr
          (hpos (laurentSpan_generator k v (Set.Ici 0) i n hn))
      rw [hz]
      exact Submodule.zero_mem _
    · by_cases hb : n ≤ b
      · have hz : N.mkQ ((T n : k[T;T⁻¹]) • v i) = 0 :=
          (Submodule.Quotient.mk_eq_zero N).mpr (hneg i n hb)
        rw [hz]
        exact Submodule.zero_mem _
      · exact Submodule.subset_span ⟨(i, ⟨n, Finset.mem_Icc.mpr ⟨by omega, by omega⟩⟩), rfl⟩
  have hle : laurentSpan k v Set.univ ≤ W.comap N.mkQ := by
    apply Submodule.span_le.mpr
    rintro x ⟨i, n, _, rfl⟩
    exact hgen i n
  rw [laurentSpan_univ, hv] at hle
  apply Submodule.eq_top_iff'.mpr
  intro z
  obtain ⟨x, rfl⟩ := N.mkQ_surjective z
  exact hle (Submodule.mem_top : x ∈ (⊤ : Submodule k[T;T⁻¹] M).restrictScalars k)

/-- Two families generating the same Laurent module yield a quotient finite
over the coefficient ring: use nonnegative powers of the first family and
nonpositive powers of the second. Only the first family needs to be finite. -/
theorem laurent_twoChart_quotient_finite [Finite ι] (v : ι → M)
    (hv : Submodule.span k[T;T⁻¹] (Set.range v) = ⊤)
    {κ : Type*} (w : κ → M) (hw : Submodule.span k[T;T⁻¹] (Set.range w) = ⊤) :
    Module.Finite k (M ⧸
      (laurentSpan k v (Set.Ici 0) ⊔ laurentSpan k w (Set.Iic 0))) := by
  classical
  have ht (i : ι) := laurent_span_eventually_nonpositive k w
    (x := v i) (by rw [hw]; exact Submodule.mem_top)
  choose b hb using ht
  obtain ⟨B, hB⟩ := (Set.finite_range b).bddBelow
  let N := laurentSpan k v (Set.Ici 0) ⊔ laurentSpan k w (Set.Iic 0)
  have hwin := laurent_twoChart_window k v hv N le_sup_left B
    (fun i n hn => (show laurentSpan k w (Set.Iic 0) ≤ N from le_sup_right)
      (hb i n (hn.trans (hB ⟨i, rfl⟩))))
  rw [Module.finite_def, ← hwin]
  exact Submodule.fg_span (Set.finite_range _)

end Normalizer
