import Normalizer.ModuleHomLine
import Mathlib.AlgebraicGeometry.Modules.Sheaf
import Mathlib.AlgebraicGeometry.IdealSheaf.Functorial
import Mathlib.AlgebraicGeometry.Morphisms.ClosedImmersion

/-! Images of actual line-sheaf maps into the structure sheaf. Local frames
identify the sectionwise image with the ideal generated by the frame image. -/

noncomputable section
set_option backward.isDefEq.respectTransparency false
namespace Normalizer
open CategoryTheory AlgebraicGeometry Opposite
universe u
variable {X : Scheme.{u}} {L : X.Modules}
  (φ : L ⟶ SheafOfModules.unit X.ringCatSheaf)

local instance schemeSectionZeroIdealSectionModule (V : X.Opensᵒᵖ) : Module (X.presheaf.obj V) (L.presheaf.obj V) :=
  (L.val.obj V).isModule

/-- The actual image on sections of a map into the structure sheaf. -/
def schemeSectionImageIdeal (V : X.Opens) : Ideal Γ(X, V) :=
  LinearMap.range (φ.val.app (op V)).hom

/-- Membership means being the image of an actual section. -/
theorem mem_schemeSectionImageIdeal (V : X.Opens) (r : Γ(X, V)) :
    r ∈ schemeSectionImageIdeal φ V ↔ ∃ s : Γ(L, V), φ.val.app (op V) s = r := Iff.rfl

/-- The zero map has the zero image ideal. -/
theorem schemeSectionImageIdeal_zero (V : X.Opens) :
    schemeSectionImageIdeal (0 : L ⟶ SheafOfModules.unit X.ringCatSheaf) V = ⊥ := by
  ext r
  change (∃ s : Γ(L, V), (0 : Γ(X, V)) = r) ↔ r = 0
  simp [eq_comm]

/-- The identity map has the unit image ideal. -/
theorem schemeSectionImageIdeal_id (V : X.Opens) :
    schemeSectionImageIdeal (𝟙 (SheafOfModules.unit X.ringCatSheaf)) V = ⊤ := by
  ext r
  simp [mem_schemeSectionImageIdeal]

/-- The local equation obtained from an actual line frame and a sheaf map. -/
def schemeSectionImageEquation {U : X.Opens}
    (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U)
    (V : X.Opens) (h : V ≤ U) : Γ(X, V) :=
  φ.val.app (op V) (moduleLineFrameAt L e V h 1)

/-- A genuine line frame proves that the actual image ideal is principal. -/
theorem schemeSectionImageIdeal_eq_span {U : X.Opens}
    (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U)
    (V : X.Opens) (h : V ≤ U) :
    schemeSectionImageIdeal φ V = Ideal.span {schemeSectionImageEquation φ e V h} := by
  ext r
  rw [mem_schemeSectionImageIdeal, Ideal.mem_span_singleton']
  constructor
  · rintro ⟨s, rfl⟩
    refine ⟨(moduleLineFrameAt L e V h).symm s, ?_⟩
    change ((moduleLineFrameAt L e V h).symm s : Γ(X, V)) •
      (φ.val.app (op V)).hom (moduleLineFrameAt L e V h 1) = _
    rw [← map_smul, ← map_smul]
    simp
  · rintro ⟨a, rfl⟩
    refine ⟨a • moduleLineFrameAt L e V h 1, ?_⟩
    exact (φ.val.app (op V)).hom.map_smul a _

/-- The frame image restricts as an actual structure-sheaf section. -/
theorem schemeSectionImageEquation_restrict {U V W : X.Opens}
    (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U)
    (h : W ≤ V) (k : V ≤ U) :
    X.presheaf.map (homOfLE h).op (schemeSectionImageEquation φ e V k) =
      schemeSectionImageEquation φ e W (h.trans k) := by
  have hn := PresheafOfModules.naturality_apply φ.val (homOfLE h).op
    (moduleLineFrameAt L e V k 1)
  change _ = _ at hn
  rw [moduleLineFrameAt_restrict L e W V h k, map_one] at hn
  exact hn.symm

/-- Inside a genuine line chart, extension of the image ideal along restriction
is exactly the image ideal on the smaller open. -/
theorem schemeSectionImageIdeal_map_of_chart {U V W : X.Opens}
    (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U)
    (h : W ≤ V) (k : V ≤ U) :
    (schemeSectionImageIdeal φ V).map (X.presheaf.map (homOfLE h).op).hom =
      schemeSectionImageIdeal φ W := by
  rw [schemeSectionImageIdeal_eq_span φ e V k,
    schemeSectionImageIdeal_eq_span φ e W (h.trans k), Ideal.map_span,
    Set.image_singleton, schemeSectionImageEquation_restrict]

/-- The actual image ideals form ideal-sheaf data on any genuine line chart.
The localization law is proved from that chart, not supplied as an assumption. -/
def schemeSectionImageIdealOn {U : X.Opens}
    (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U) :
    U.toScheme.IdealSheafData where
  ideal V := schemeSectionImageIdeal φ (U.ι ''ᵁ V.1)
  map_ideal_basicOpen V f := by
    exact schemeSectionImageIdeal_map_of_chart φ e
      (leOfHom (U.ι.opensFunctor.map
        (homOfLE (U.toScheme.basicOpen_le f)))) (U.ι_image_le V.1)

/-- On every affine open in the chart this is exactly the image of the given
sheaf map on the corresponding open of the original scheme. -/
theorem schemeSectionImageIdealOn_ideal {U : X.Opens}
    (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U)
    (V : U.toScheme.affineOpens) :
    (schemeSectionImageIdealOn φ e).ideal V =
      schemeSectionImageIdeal φ (U.ι ''ᵁ V.1) := rfl

/-- Each affine chart of the zero subscheme is cut out by the actual frame image. -/
theorem schemeSectionImageIdealOn_ideal_eq_span {U : X.Opens}
    (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U)
    (V : U.toScheme.affineOpens) :
    (schemeSectionImageIdealOn φ e).ideal V =
      Ideal.span {schemeSectionImageEquation φ e (U.ι ''ᵁ V.1) (U.ι_image_le V.1)} :=
  schemeSectionImageIdeal_eq_span φ e _ _

/-- Changing the frame does not change the actual image ideal sheaf. -/
theorem schemeSectionImageIdealOn_eq {U : X.Opens}
    (e e' : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U) :
    schemeSectionImageIdealOn φ e = schemeSectionImageIdealOn φ e' := by
  apply Scheme.IdealSheafData.ext
  rfl

private theorem imageIdeal_comap_of_eq {V W : X.Opens} (h : W ≤ V) (he : W = V) :
    (schemeSectionImageIdeal φ W).comap (X.presheaf.map (homOfLE h).op).hom =
      schemeSectionImageIdeal φ V := by
  subst W
  simp

/-- The local image ideal sheaves agree under restriction to a smaller chart. -/
theorem schemeSectionImageIdealOn_comap {U V : X.Opens}
    (eU : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U)
    (eV : (SheafOfModules.unit X.ringCatSheaf).over V ≅ L.over V)
    (h : U ≤ V) :
    (schemeSectionImageIdealOn φ eV).comap (X.homOfLE h) =
      schemeSectionImageIdealOn φ eU := by
  apply Scheme.IdealSheafData.ext
  funext W
  rw [Scheme.IdealSheafData.ideal_comap_of_isOpenImmersion]
  simp only [schemeSectionImageIdealOn_ideal, Scheme.Hom.appIso_homOfLE_inv]
  have he : V.ι ''ᵁ ((X.homOfLE h) ''ᵁ W.1) = U.ι ''ᵁ W.1 := by
    simp only [← Scheme.Hom.comp_image, Scheme.homOfLE_ι]
  exact imageIdeal_comap_of_eq φ _ he

/-- The actual zero subscheme on a genuine line chart. -/
def schemeSectionZeroSubschemeOn {U : X.Opens}
    (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U) : Scheme :=
  (schemeSectionImageIdealOn φ e).subscheme

/-- The zero subscheme is equipped with its closed immersion into the chart. -/
def schemeSectionZeroSubschemeOnι {U : X.Opens}
    (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U) :
    schemeSectionZeroSubschemeOn φ e ⟶ U.toScheme :=
  (schemeSectionImageIdealOn φ e).subschemeι

/-- The constructed morphism is a closed immersion, including nilpotent structure. -/
theorem schemeSectionZeroSubschemeOn_isClosedImmersion {U : X.Opens}
    (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U) :
    IsClosedImmersion (schemeSectionZeroSubschemeOnι φ e) := by
  dsimp [schemeSectionZeroSubschemeOnι]
  infer_instance

/-- The zero subscheme on a smaller chart is the actual base change of the
zero subscheme on the larger chart. -/
def schemeSectionZeroSubschemeOnPullbackIso {U V : X.Opens}
    (eU : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U)
    (eV : (SheafOfModules.unit X.ringCatSheaf).over V ≅ L.over V)
    (h : U ≤ V) :
    schemeSectionZeroSubschemeOn φ eU ≅
      Limits.pullback (X.homOfLE h) (schemeSectionZeroSubschemeOnι φ eV) :=
  eqToIso (congrArg Scheme.IdealSheafData.subscheme
    (schemeSectionImageIdealOn_comap φ eU eV h).symm) ≪≫
      (schemeSectionImageIdealOn φ eV).comapIso (X.homOfLE h)

end Normalizer
