import Normalizer.SectionLocalEquation
import Normalizer.SectionDualEvaluation
import Normalizer.SectionZeroIdeal

/-! The actual dual-evaluation ideal of a specified section has its actual
local equation as generator. Generic nonzeroness proves Cartier regularity
of these equations on an integral scheme. -/

noncomputable section
set_option backward.isDefEq.respectTransparency false
namespace Normalizer
open CategoryTheory AlgebraicGeometry Opposite
universe u

variable {X : Scheme.{u}} (L : X.Modules) (s : Γ(L, ⊤))
  {U : X.Opens} (e : (SheafOfModules.unit X.ringCatSheaf).over U ≅ L.over U)

/-- The image equation of actual dual evaluation is exactly the original
specified section's local equation, in the constructed dual chart. -/
theorem schemeSectionDualEvaluation_equation (V : X.Opens) (h : V ≤ U) :
    schemeSectionImageEquation (schemeSectionDualEvaluation L s)
      (schemeDualLineFrameIso L e) V h = sectionLocalEquation L s e V h :=
  schemeSectionDualEvaluation_frame_one L s e V h

/-- The actual image ideal, rather than an unrelated principal ideal,
is generated by the specified section's local equation. -/
theorem schemeSectionDualEvaluation_imageIdeal (V : X.Opens) (h : V ≤ U) :
    schemeSectionImageIdeal (schemeSectionDualEvaluation L s) V =
      Ideal.span {sectionLocalEquation L s e V h} := by
  rw [schemeSectionImageIdeal_eq_span (schemeSectionDualEvaluation L s)
    (schemeDualLineFrameIso L e) V h, schemeSectionDualEvaluation_equation]

/-- The same equality after mapping to the actual local ring at a point. -/
theorem schemeSectionDualEvaluation_germ_imageIdeal
    (V : X.Opens) (h : V ≤ U) (x : X) (hx : x ∈ V) :
    (schemeSectionImageIdeal (schemeSectionDualEvaluation L s) V).map
      (X.presheaf.germ V x hx).hom =
        Ideal.span {X.presheaf.germ V x hx (sectionLocalEquation L s e V h)} := by
  rw [schemeSectionDualEvaluation_imageIdeal L s e V h,
    Ideal.map_span, Set.image_singleton]

/-- The local image ideal is the unit ideal exactly where the equation
is invertible. This is stronger than its nonzeroness in a domain. -/
theorem schemeSectionDualEvaluation_imageIdeal_eq_top_iff
    (V : X.Opens) (h : V ≤ U) :
    schemeSectionImageIdeal (schemeSectionDualEvaluation L s) V = ⊤ ↔
      IsUnit (sectionLocalEquation L s e V h) := by
  rw [schemeSectionDualEvaluation_imageIdeal L s e V h, Ideal.span_singleton_eq_top]

/-- The actual local-ring image ideal detects zeros by noninvertibility
of the specified equation in that local ring. -/
theorem schemeSectionDualEvaluation_germ_imageIdeal_eq_top_iff
    (V : X.Opens) (h : V ≤ U) (x : X) (hx : x ∈ V) :
    (schemeSectionImageIdeal (schemeSectionDualEvaluation L s) V).map
      (X.presheaf.germ V x hx).hom = ⊤ ↔
        IsUnit (X.presheaf.germ V x hx (sectionLocalEquation L s e V h)) := by
  rw [schemeSectionDualEvaluation_germ_imageIdeal L s e V h x hx,
    Ideal.span_singleton_eq_top]

include e in
/-- The actual local-ring image ideal has a non-zero-divisor generator
when the prescribed section has nonzero generic germ on an integral scheme. -/
theorem schemeSectionDualEvaluation_germ_imageIdeal_regular
    [IsIntegral X]
    (hs : L.presheaf.germ ⊤ (genericPoint X) (by trivial) s ≠ 0)
    (V : X.Opens) (h : V ≤ U) (x : X) (hx : x ∈ V) :
    ∃ r : X.presheaf.stalk x, IsRegular r ∧
      (schemeSectionImageIdeal (schemeSectionDualEvaluation L s) V).map
        (X.presheaf.germ V x hx).hom = Ideal.span {r} :=
  ⟨_, sectionLocalEquation_germ_isRegular L s e hs V h x hx,
    schemeSectionDualEvaluation_germ_imageIdeal L s e V h x hx⟩

end Normalizer
